import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useQuery } from "@tanstack/react-query";
import Sidebar from "../../components/layout/Sidebar";
import { apiRequest } from "../../lib/queryClient";
import { useAuth } from "../../hooks/useAuth";
export default function AlunoCaixa() {
    const { auth } = useAuth();
    const { data: movimentos = [] } = useQuery({ queryKey: ["caixa"], queryFn: () => apiRequest("GET", "/caixa"), enabled: !!auth });
    const { data: saldoData } = useQuery({ queryKey: ["caixa-saldo"], queryFn: () => apiRequest("GET", "/caixa/saldo"), enabled: !!auth });
    const fmt = (v) => parseFloat(String(v || 0)).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
    return (_jsxs("div", { className: "flex min-h-screen", children: [_jsx(Sidebar, { role: "aluno" }), _jsxs("main", { className: "flex-1 ml-64 p-8 space-y-6", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-3xl font-black", children: "Caixa Transparente" }), _jsx("p", { className: "text-slate-500", children: "Toda movimenta\u00E7\u00E3o financeira da turma, com total transpar\u00EAncia." })] }), _jsxs("div", { className: "card p-8 text-center bg-gradient-to-br from-primary/10 to-transparent border-blue-200 dark:border-blue-800/30", children: [_jsxs("div", { className: "flex items-center justify-center gap-2 mb-2", children: [_jsx("span", { className: "material-symbols-outlined text-primary", children: "account_balance" }), _jsx("p", { className: "text-sm font-bold uppercase text-slate-500 tracking-widest", children: "Saldo Atual" })] }), _jsx("p", { className: "text-5xl font-black text-primary", children: fmt(saldoData?.saldo ?? 0) }), _jsx("p", { className: "text-sm text-slate-400 mt-2", children: "Atualizado em tempo real" })] }), _jsxs("div", { className: "card overflow-hidden", children: [_jsx("div", { className: "px-6 py-4 border-b border-slate-200 dark:border-slate-800", children: _jsx("h4", { className: "font-bold", children: "Extrato de Movimenta\u00E7\u00F5es" }) }), _jsxs("div", { className: "divide-y divide-slate-100 dark:divide-slate-800", children: [movimentos.map((row, i) => (_jsxs("div", { className: "px-6 py-4 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: `size-10 rounded-full flex items-center justify-center ${row.mov?.tipo === "entrada" ? "bg-emerald-100 dark:bg-emerald-900/30" : "bg-rose-100 dark:bg-rose-900/30"}`, children: _jsx("span", { className: `material-symbols-outlined text-sm ${row.mov?.tipo === "entrada" ? "text-emerald-600" : "text-rose-500"}`, children: row.mov?.tipo === "entrada" ? "arrow_downward" : "arrow_upward" }) }), _jsxs("div", { children: [_jsx("p", { className: "font-semibold text-sm", children: row.mov?.descricao }), _jsxs("p", { className: "text-xs text-slate-500", children: [row.usuario?.nome && `Por ${row.usuario.nome} • `, row.mov?.data ? new Date(row.mov.data).toLocaleDateString("pt-BR") : ""] })] })] }), _jsxs("p", { className: `font-black text-lg ${row.mov?.tipo === "entrada" ? "text-emerald-600" : "text-rose-500"}`, children: [row.mov?.tipo === "entrada" ? "+" : "-", fmt(row.mov?.valor)] })] }, row.mov?.id ?? i))), movimentos.length === 0 && _jsx("div", { className: "px-6 py-12 text-center text-slate-400", children: "Nenhuma movimenta\u00E7\u00E3o registrada." })] })] })] })] }));
}
