import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useQuery } from "@tanstack/react-query";
import Sidebar from "../../components/layout/Sidebar";
import { apiRequest } from "../../lib/queryClient";
import { useAuth } from "../../hooks/useAuth";
export default function AlunoPagamentos() {
    const { auth } = useAuth();
    const { data: pagamentos = [] } = useQuery({ queryKey: ["meus-pagamentos"], queryFn: () => apiRequest("GET", "/pagamentos"), enabled: !!auth });
    const fmt = (v) => parseFloat(String(v || 0)).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
    const total = pagamentos.reduce((s, p) => s + parseFloat(p.valor || 0), 0);
    const pago = pagamentos.filter((p) => p.status === "pago").reduce((s, p) => s + parseFloat(p.valor || 0), 0);
    const pendente = total - pago;
    return (_jsxs("div", { className: "flex min-h-screen", children: [_jsx(Sidebar, { role: "aluno" }), _jsxs("main", { className: "flex-1 ml-64 p-8 space-y-6", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-3xl font-black", children: "Meus Pagamentos" }), _jsx("p", { className: "text-slate-500", children: "Acompanhe suas mensalidades e taxas." })] }), _jsx("div", { className: "grid grid-cols-3 gap-4", children: [
                            { label: "Total", value: fmt(total), icon: "payments", color: "text-slate-600" },
                            { label: "Pago", value: fmt(pago), icon: "check_circle", color: "text-emerald-500" },
                            { label: "Pendente", value: fmt(pendente), icon: "schedule", color: "text-amber-500" },
                        ].map(s => (_jsxs("div", { className: "card p-5", children: [_jsxs("div", { className: "flex items-center gap-2 mb-2", children: [_jsx("span", { className: `material-symbols-outlined ${s.color}`, children: s.icon }), _jsx("span", { className: "text-xs font-bold uppercase text-slate-400", children: s.label })] }), _jsx("p", { className: "text-2xl font-black", children: s.value })] }, s.label))) }), _jsxs("div", { className: "card overflow-hidden", children: [_jsx("div", { className: "px-6 py-4 border-b border-slate-200 dark:border-slate-800", children: _jsx("h4", { className: "font-bold", children: "Hist\u00F3rico" }) }), _jsxs("div", { className: "divide-y divide-slate-100 dark:divide-slate-800", children: [pagamentos.map((p, i) => (_jsxs("div", { className: "px-6 py-4 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: `size-10 rounded-full border-2 flex items-center justify-center ${p.status === "pago" ? "border-primary bg-blue-50 dark:bg-blue-900/20" : "border-slate-200"}`, children: _jsx("span", { className: `material-symbols-outlined text-sm ${p.status === "pago" ? "text-primary" : "text-slate-400"}`, children: p.status === "pago" ? "check" : "schedule" }) }), _jsxs("div", { children: [_jsx("p", { className: "font-semibold text-sm", children: p.descricao }), _jsx("p", { className: "text-xs text-slate-500", children: p.dataVencimento ? `Venc.: ${new Date(p.dataVencimento).toLocaleDateString("pt-BR")}` : "Sem vencimento" })] })] }), _jsxs("div", { className: "text-right", children: [_jsx("p", { className: "font-black", children: fmt(p.valor) }), _jsx("span", { className: p.status === "pago" ? "badge-success" : p.status === "atrasado" ? "badge-danger" : "badge-warning", children: p.status === "pago" ? "Pago" : p.status === "atrasado" ? "Atrasado" : "Pendente" })] })] }, p.id ?? i))), pagamentos.length === 0 && _jsx("div", { className: "px-6 py-12 text-center text-slate-400", children: "Nenhum pagamento registrado." })] })] })] })] }));
}
