import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useQuery } from "@tanstack/react-query";
import Sidebar from "../../components/layout/Sidebar";
import { apiRequest } from "../../lib/queryClient";
import { useAuth } from "../../hooks/useAuth";
export default function AlunoPerfil() {
    const { auth, logout } = useAuth();
    const { data: me } = useQuery({ queryKey: ["me"], queryFn: () => apiRequest("GET", "/alunos/me"), enabled: !!auth });
    return (_jsxs("div", { className: "flex min-h-screen", children: [_jsx(Sidebar, { role: "aluno" }), _jsxs("main", { className: "flex-1 ml-64 p-8 space-y-6 max-w-2xl", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-3xl font-black", children: "Meu Perfil" }), _jsx("p", { className: "text-slate-500", children: "Suas informa\u00E7\u00F5es de conta." })] }), _jsxs("div", { className: "card p-6 flex items-center gap-6", children: [_jsx("div", { className: "size-20 rounded-full bg-primary flex items-center justify-center text-white text-3xl font-black shrink-0", children: me?.nome?.charAt(0) || "?" }), _jsxs("div", { children: [_jsx("h3", { className: "text-2xl font-black", children: me?.nome }), _jsx("p", { className: "text-slate-500", children: me?.email }), _jsx("span", { className: "badge-success mt-2", children: "Aluno Ativo" })] })] }), _jsxs("div", { className: "card p-6 space-y-4", children: [_jsx("h4", { className: "font-semibold", children: "Informa\u00E7\u00F5es Pessoais" }), _jsxs("div", { children: [_jsx("label", { className: "text-sm font-semibold text-slate-700 dark:text-slate-300 block mb-1", children: "Nome" }), _jsx("input", { className: "input", defaultValue: me?.nome })] }), _jsxs("div", { children: [_jsx("label", { className: "text-sm font-semibold text-slate-700 dark:text-slate-300 block mb-1", children: "E-mail" }), _jsx("input", { className: "input opacity-60 cursor-not-allowed", type: "email", defaultValue: me?.email, disabled: true })] }), _jsx("button", { className: "btn-primary", children: "Salvar Altera\u00E7\u00F5es" })] }), _jsxs("div", { className: "card p-6 space-y-4", children: [_jsx("h4", { className: "font-semibold", children: "Alterar Senha" }), _jsx("input", { className: "input", type: "password", placeholder: "Senha atual" }), _jsx("input", { className: "input", type: "password", placeholder: "Nova senha" }), _jsx("button", { className: "btn-secondary", children: "Atualizar Senha" })] }), _jsxs("button", { onClick: () => logout.mutate(), className: "w-full flex items-center justify-center gap-2 py-3 rounded-lg border border-red-200 text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20 transition-colors font-semibold", children: [_jsx("span", { className: "material-symbols-outlined text-sm", children: "logout" }), "Sair da conta"] })] })] }));
}
