import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useQuery } from "@tanstack/react-query";
import Sidebar from "../../components/layout/Sidebar";
import Header from "../../components/layout/Header";
import { apiRequest } from "../../lib/queryClient";
export default function AdminRanking() {
    const { data: alunos = [] } = useQuery({ queryKey: ["alunos"], queryFn: () => apiRequest("GET", "/alunos") });
    const { data: pagamentos = [] } = useQuery({ queryKey: ["pagamentos"], queryFn: () => apiRequest("GET", "/pagamentos") });
    const ranking = alunos.map((a) => {
        const pags = pagamentos.filter((p) => p.pagamento?.usuarioId === a.id);
        const total = pags.reduce((s, p) => s + parseFloat(p.pagamento?.valor || "0"), 0);
        const pagos = pags.filter((p) => p.pagamento?.status === "pago").length;
        return { ...a, totalPago: total, qtdPagamentos: pagos };
    }).sort((a, b) => b.totalPago - a.totalPago);
    const fmt = (v) => v.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
    const medals = ["🥇", "🥈", "🥉"];
    return (_jsxs("div", { className: "flex h-screen overflow-hidden", children: [_jsx(Sidebar, { role: "admin" }), _jsxs("main", { className: "flex-1 flex flex-col overflow-y-auto ml-64", children: [_jsx(Header, { title: "Ranking" }), _jsxs("div", { className: "p-8 space-y-6", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-xl font-bold", children: "Ranking de Alunos" }), _jsx("p", { className: "text-sm text-slate-500", children: "Por total de pagamentos realizados" })] }), ranking.length >= 3 && (_jsx("div", { className: "grid grid-cols-3 gap-4", children: ranking.slice(0, 3).map((a, i) => (_jsxs("div", { className: `card p-6 text-center ${i === 0 ? "border-yellow-300 dark:border-yellow-600/50 shadow-lg" : ""}`, children: [_jsx("div", { className: "text-4xl mb-3", children: medals[i] }), _jsx("div", { className: "size-14 rounded-full bg-primary mx-auto flex items-center justify-center text-white font-black text-xl mb-3", children: a.nome?.charAt(0) }), _jsx("p", { className: "font-bold", children: a.nome }), _jsx("p", { className: "text-lg font-black text-primary mt-1", children: fmt(a.totalPago) }), _jsxs("p", { className: "text-xs text-slate-500", children: [a.qtdPagamentos, " pagamentos"] })] }, a.id))) })), _jsx("div", { className: "card overflow-hidden", children: _jsxs("table", { className: "w-full text-left", children: [_jsx("thead", { children: _jsx("tr", { className: "bg-slate-50 dark:bg-slate-800/50", children: ["#", "Aluno", "Pagamentos", "Total Pago"].map(h => (_jsx("th", { className: "px-6 py-3.5 text-[10px] font-bold text-slate-400 uppercase tracking-widest", children: h }, h))) }) }), _jsxs("tbody", { className: "divide-y divide-slate-100 dark:divide-slate-800", children: [ranking.map((a, i) => (_jsxs("tr", { className: "hover:bg-slate-50/80 dark:hover:bg-slate-800/40 transition-colors", children: [_jsx("td", { className: "px-6 py-4 font-bold text-slate-400 text-sm", children: i < 3 ? medals[i] : `#${i + 1}` }), _jsx("td", { className: "px-6 py-4", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "size-9 rounded-full bg-primary flex items-center justify-center text-white font-bold text-sm", children: a.nome?.charAt(0) }), _jsx("span", { className: "font-semibold text-sm", children: a.nome })] }) }), _jsx("td", { className: "px-6 py-4 text-sm", children: a.qtdPagamentos }), _jsx("td", { className: "px-6 py-4 font-bold text-primary", children: fmt(a.totalPago) })] }, a.id))), ranking.length === 0 && _jsx("tr", { children: _jsx("td", { colSpan: 4, className: "px-6 py-12 text-center text-slate-400", children: "Nenhum dado dispon\u00EDvel." }) })] })] }) })] })] })] }));
}
