import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from "react-router-dom";
import ThemeToggle from "../ThemeToggle";
export default function MobileHeader({ title, subtitle, showBack = false, actions = [], gradient = false, gold = false, className = "", }) {
    const navigate = useNavigate();
    if (gradient) {
        return (_jsxs("header", { className: `mobile-header-gradient ${className}`, children: [_jsxs("div", { className: "flex items-center gap-3", children: [showBack && (_jsx("button", { onClick: () => navigate(-1), className: "p-2 -ml-2 rounded-xl hover:bg-white/20 active:bg-white/30 transition-colors", children: _jsx("span", { className: "material-symbols-outlined text-white", children: "arrow_back" }) })), _jsxs("div", { children: [_jsx("h1", { className: "text-lg font-bold text-white leading-tight", children: title }), subtitle && (_jsx("p", { className: "text-xs text-indigo-200 font-medium", children: subtitle }))] })] }), _jsxs("div", { className: "flex items-center gap-1", children: [actions.map((action, i) => (_jsx("button", { onClick: action.onClick, "aria-label": action.label, className: "p-2 rounded-xl hover:bg-white/20 active:bg-white/30 transition-colors", children: _jsx("span", { className: "material-symbols-outlined text-white text-xl", children: action.icon }) }, i))), _jsx(ThemeToggle, {})] })] }));
    }
    if (gold) {
        return (_jsxs("header", { className: `mobile-header-gold ${className}`, children: [_jsxs("div", { className: "flex items-center gap-3", children: [showBack && (_jsx("button", { onClick: () => navigate(-1), className: "p-2 -ml-2 rounded-xl hover:bg-white/20 active:bg-white/30 transition-colors", children: _jsx("span", { className: "material-symbols-outlined text-white", children: "arrow_back" }) })), _jsxs("div", { children: [_jsx("h1", { className: "text-lg font-bold text-white leading-tight", children: title }), subtitle && (_jsx("p", { className: "text-xs text-amber-100 font-medium", children: subtitle }))] })] }), _jsxs("div", { className: "flex items-center gap-1", children: [actions.map((action, i) => (_jsx("button", { onClick: action.onClick, "aria-label": action.label, className: "p-2 rounded-xl hover:bg-white/20 active:bg-white/30 transition-colors", children: _jsx("span", { className: "material-symbols-outlined text-white text-xl", children: action.icon }) }, i))), _jsx(ThemeToggle, {})] })] }));
    }
    return (_jsxs("header", { className: `mobile-header ${className}`, children: [_jsxs("div", { className: "flex items-center gap-3", children: [showBack && (_jsx("button", { onClick: () => navigate(-1), className: "p-2 -ml-2 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800 active:bg-slate-200 transition-colors", children: _jsx("span", { className: "material-symbols-outlined text-slate-700 dark:text-slate-200", children: "arrow_back" }) })), _jsxs("div", { children: [_jsx("h1", { className: "text-base font-bold text-slate-900 dark:text-white leading-tight", children: title }), subtitle && (_jsx("p", { className: "text-xs text-slate-500 dark:text-slate-400 font-medium", children: subtitle }))] })] }), _jsxs("div", { className: "flex items-center gap-1", children: [actions.map((action, i) => (_jsx("button", { onClick: action.onClick, "aria-label": action.label, className: "p-2 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors text-slate-600 dark:text-slate-300", children: _jsx("span", { className: "material-symbols-outlined text-xl", children: action.icon }) }, i))), _jsx(ThemeToggle, {})] })] }));
}
