import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from "react-router-dom";
export default function ModalCompra({ onClose }) {
    const navigate = useNavigate();
    const handleWhatsApp = (tipo) => {
        const numero = "19997639130";
        const mensagem = tipo === "compra"
            ? "Quero comprar o Organize+ Pro"
            : "Quero saber mais sobre o Organize+ Pro";
        window.open(`https://wa.me/${numero}?text=${encodeURIComponent(mensagem)}`, "_blank");
    };
    return (_jsx("div", { className: "fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm animate-fade-in", children: _jsxs("div", { className: "w-full max-w-[400px] bg-white dark:bg-slate-900 rounded-xl shadow-2xl overflow-hidden flex flex-col border border-slate-200 dark:border-slate-800", children: [_jsxs("header", { className: "flex items-center justify-between px-6 py-4 border-b border-slate-100 dark:border-slate-800", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "text-[#c6a43f]", children: _jsx("span", { className: "material-symbols-outlined font-bold", children: "bolt" }) }), _jsx("h2", { className: "text-[#1e3a5f] dark:text-slate-100 text-sm font-bold tracking-wider uppercase", children: "Acesso Vital\u00EDcio" })] }), _jsx("button", { onClick: onClose, className: "p-1.5 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg transition-colors text-slate-400", children: _jsx("span", { className: "material-symbols-outlined text-xl", children: "close" }) })] }), _jsxs("div", { className: "p-6 flex flex-col", children: [_jsxs("div", { className: "flex items-center gap-2 mb-6", children: [_jsx("div", { className: "w-8 h-8 bg-[#c6a43f] rounded-lg flex items-center justify-center text-[#1e3a5f]", children: _jsx("span", { className: "material-symbols-outlined text-lg", children: "grid_view" }) }), _jsx("span", { className: "font-bold text-[#1e3a5f] dark:text-slate-100", children: "Organize+ Pro" })] }), _jsxs("div", { className: "mb-8", children: [_jsxs("div", { className: "flex items-baseline gap-1", children: [_jsx("span", { className: "text-4xl font-extrabold text-[#1e3a5f] dark:text-slate-100 tracking-tight", children: "R$ 500" }), _jsx("span", { className: "text-slate-500 dark:text-slate-400 font-medium", children: "/ \u00FAnico" })] }), _jsx("p", { className: "text-[#c6a43f] font-medium text-sm mt-1", children: "Menos de R$ 20 por aluno" })] }), _jsx("div", { className: "space-y-4 mb-8", children: [
                                "Gestão completa de turmas",
                                "Rifas e sorteios ilimitados",
                                "Transparência total para pais",
                                "Suporte prioritário 24/7"
                            ].map((benefit) => (_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "flex-shrink-0 w-5 h-5 rounded-full bg-[#c6a43f]/10 flex items-center justify-center", children: _jsx("span", { className: "material-symbols-outlined text-[#c6a43f] text-sm font-bold", children: "check" }) }), _jsx("p", { className: "text-slate-700 dark:text-slate-300 text-sm", children: benefit })] }, benefit))) }), _jsxs("div", { className: "flex flex-col gap-3", children: [_jsxs("button", { onClick: () => handleWhatsApp("compra"), className: "w-full bg-[#c6a43f] hover:bg-[#b89430] text-[#1e3a5f] font-bold py-3.5 rounded-lg flex items-center justify-center gap-2 transition-all shadow-lg shadow-[#c6a43f]/20", children: [_jsx("span", { className: "material-symbols-outlined text-xl", children: "shopping_cart" }), _jsx("span", { children: "Comprar agora" })] }), _jsxs("button", { onClick: () => handleWhatsApp("duvida"), className: "w-full bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-[#1e3a5f] dark:text-slate-100 font-bold py-3.5 rounded-lg flex items-center justify-center gap-2 transition-all", children: [_jsx("span", { className: "material-symbols-outlined text-xl", children: "chat" }), _jsx("span", { children: "Saber mais" })] })] })] }), _jsx("footer", { className: "bg-slate-50 dark:bg-slate-800/50 p-4 border-t border-slate-100 dark:border-slate-800 flex justify-center", children: _jsxs("a", { onClick: () => {
                            onClose();
                            navigate("/acesso");
                        }, className: "text-[#c6a43f] hover:text-[#b89430] text-sm font-semibold flex items-center gap-1 transition-colors cursor-pointer", children: [_jsx("span", { className: "material-symbols-outlined text-lg", children: "vpn_key" }), "J\u00E1 tenho chave de acesso"] }) })] }) }));
}
